[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "langchain-community>=0.3.24",
    "langchain>=0.3.25",
    "langchain-google-genai>=2.1.4",
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.1",
]
